export enum TrainerSpecialization {
  STRENGTH_TRAINING = 'Strength Training',
  YOGA = 'Yoga',
  CARDIO = 'Cardio',
  PILATES = 'Pilates',
  BODYBUILDING = 'Bodybuilding',
  CROSSFIT = 'CrossFit',
  FUNCTIONAL_TRAINING = 'Functional Training',
  AEROBICS = 'Aerobics',
  ZUMBA = 'Zumba',
  SPINNING = 'Spinning',
  BOOTCAMP = 'Bootcamp',
  MARTIAL_ARTS = 'Martial Arts',
  BOXING = 'Boxing',
  POWERLIFTING = 'Powerlifting',
  OLYMPIC_WEIGHTLIFTING = 'Olympic Weightlifting',
  HIIT = 'High-Intensity Interval Training (HIIT)',
  TABATA = 'Tabata',
  CALISTHENICS = 'Calisthenics',
  REHABILITATIVE_EXERCISES = 'Rehabilitative Exercises',
  SENIOR_FITNESS = 'Senior Fitness',
  PREGNANCY_FITNESS = 'Pregnancy Fitness',
}
